### ISSUE TITLE
KMP + Xcode 5.4 - Error: `ld: symbol(s) not found for architecture arm64`

### ISSUE THREAD

**Issue by robertjamison** [googleads/swift-package-manager-google-mobile-ads#103]
During a KMP build using Swift Package Manager, I consistently get this error:
```yaml
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_JSContext", referenced from:
       in GoogleMobileAds[arm64][421](GADOMIDLightJSExecutor.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
It occurs with any project I use that incorporates the `swift-package-manager-google-mobile-ads` dependency.
It also unlinks any other Swift Package Manager dependencies that were working before.

**Platform Info:**
```yaml
Google Mobile Ads: Version 11.9.0+
Xcode: Version 15.4 (15F31d)
Android Studio: Koala Feature Drop | 2024.1.2
Gradle: Version 8.7
```
